In [3]:
from tensorflow.keras.preprocessing.text import one_hot

In [4]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [5]:
## Define the vocabulary size
voc_size=10000

In [6]:
### One Hot Representation
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr

[[2364, 4372, 4279, 9582],
 [2364, 4372, 4279, 3876],
 [2364, 8995, 4279, 3884],
 [2900, 6987, 1826, 2656, 1329],
 [2900, 6987, 1826, 2656, 2454],
 [1988, 2364, 7768, 4279, 3308],
 [2741, 8431, 7531, 2656]]

In [7]:
import numpy as np 
## word Embedding Representation

from tensorflow.keras.layers import Embedding
#from tensorflow.keras.processing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [8]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 2364 4372 4279 9582]
 [   0    0    0    0 2364 4372 4279 3876]
 [   0    0    0    0 2364 8995 4279 3884]
 [   0    0    0 2900 6987 1826 2656 1329]
 [   0    0    0 2900 6987 1826 2656 2454]
 [   0    0    0 1988 2364 7768 4279 3308]
 [   0    0    0    0 2741 8431 7531 2656]]


In [9]:
dim=10

In [10]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

c:\Users\BIT\OneDrive - Birla Institute of Technology\Desktop\DL_PROJECT\aienv\Lib\site-packages\keras\src\layers\core\embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [11]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [12]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 203ms/step


array([[[-4.3672062e-02,  2.8681878e-02, -8.4125288e-03,  2.4174679e-02,
         -1.4410771e-02, -3.0875588e-02,  2.9050235e-02,  4.6722833e-02,
         -2.5512446e-02, -3.7267506e-02],
        [-4.3672062e-02,  2.8681878e-02, -8.4125288e-03,  2.4174679e-02,
         -1.4410771e-02, -3.0875588e-02,  2.9050235e-02,  4.6722833e-02,
         -2.5512446e-02, -3.7267506e-02],
        [-4.3672062e-02,  2.8681878e-02, -8.4125288e-03,  2.4174679e-02,
         -1.4410771e-02, -3.0875588e-02,  2.9050235e-02,  4.6722833e-02,
         -2.5512446e-02, -3.7267506e-02],
        [-4.3672062e-02,  2.8681878e-02, -8.4125288e-03,  2.4174679e-02,
         -1.4410771e-02, -3.0875588e-02,  2.9050235e-02,  4.6722833e-02,
         -2.5512446e-02, -3.7267506e-02],
        [ 3.1581748e-02,  3.9813351e-02,  3.4869909e-03,  3.9905023e-02,
         -1.8143810e-02, -4.6385229e-02,  3.9759669e-02, -4.0990196e-02,
         -6.7201033e-03,  3.1178523e-02],
        [ 1.7590966e-02,  3.9309535e-02, -3.2646347e-02, -3.